# Generated by Django 5.0.2 on 2024-03-05 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_fotografia_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
